#!/usr/bin/env python3
"""Generate the validator index in README.md from each package's pyproject.toml.

The index is the machine-readable catalog of this repo: the Guardrails validator
hub UI (https://guardrailsai.com/hub) fetches this README and parses the index to
populate its validator list and detail pages, so the format below is a contract —
one entry per validator, one line each:

    * [Display Name](pypi link): Description. [Code](link to the package README)

Per-package metadata comes from `<name>/py/pyproject.toml`:

    [project]
    name = "guardrails-ai-<name>"
    description = "One-line description of the validator."

    [tool.guardrails]
    display-name = "Display Name"
    tags = ["Data Leakage", "Chatbots", "string", "ML"]

Tags aren't rendered into the index — pyproject.toml is their single home, and the
hub UI reads them from there.

Usage:
    python scripts/generate_validators_index.py           # rewrite README.md
    python scripts/generate_validators_index.py --check    # fail if out of date
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN VALIDATOR INDEX -->"
END = "<!-- END VALIDATOR INDEX -->"
REPO_BLOB = "https://github.com/guardrails-ai/guardrails-hub-monorepo/blob/main"


def load_validators() -> list[dict]:
    validators = []
    for pyproject in sorted(ROOT.glob("*/py/pyproject.toml")):
        package_dir = pyproject.parent.parent.name
        with pyproject.open("rb") as handle:
            config = tomllib.load(handle)

        project = config["project"]
        guardrails = config.get("tool", {}).get("guardrails", {})
        missing = [
            key for key in ("display-name", "tags") if not guardrails.get(key)
        ]
        if missing:
            raise SystemExit(
                f"{package_dir}/py/pyproject.toml: [tool.guardrails] is missing "
                f"{', '.join(missing)}"
            )
        if not project.get("description"):
            raise SystemExit(
                f"{package_dir}/py/pyproject.toml: [project] description is required"
            )

        validators.append(
            {
                "dir": package_dir,
                "dist": project["name"],
                "name": guardrails["display-name"],
                "description": project["description"].strip(),
                "tags": list(guardrails["tags"]),
            }
        )

    validators.sort(key=lambda validator: validator["name"].lower())
    return validators


def render_index(validators: list[dict]) -> str:
    lines = [
        BEGIN,
        "<!-- Generated by scripts/generate_validators_index.py — do not edit by hand. -->",
        "## All Hub Validators",
        "",
        f"{len(validators)} validators. Each is a standalone PyPI package — install it with "
        "`pip install <package>`; no account, API key, or hub login is required.",
        "",
    ]
    for validator in validators:
        pypi = f"https://pypi.org/project/{validator['dist']}/"
        code = f"{REPO_BLOB}/{validator['dir']}/py/README.md"
        description = validator["description"]
        if not description.endswith((".", "!", "?")):
            description += "."
        lines.append(
            f"* [{validator['name']}]({pypi}): {description} [Code]({code})"
        )
    lines += ["", END]
    return "\n".join(lines)


def splice(readme: str, index: str) -> str:
    if BEGIN not in readme or END not in readme:
        raise SystemExit(
            f"README.md is missing the {BEGIN} / {END} markers around the index"
        )
    start = readme.index(BEGIN)
    end = readme.index(END) + len(END)
    return readme[:start] + index + readme[end:]


def main() -> int:
    check = "--check" in sys.argv[1:]
    validators = load_validators()
    current = README.read_text()
    updated = splice(current, render_index(validators))

    if check:
        if current != updated:
            print(
                "README.md validator index is out of date. Run:\n"
                "  python scripts/generate_validators_index.py",
                file=sys.stderr,
            )
            return 1
        print(f"README.md validator index is up to date ({len(validators)} validators).")
        return 0

    if current == updated:
        print(f"README.md already up to date ({len(validators)} validators).")
        return 0

    README.write_text(updated)
    print(f"Wrote {len(validators)} validators to README.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
